spring.config.import=optional:file:./backend-spring/.env[.properties]
server.port=8081
spring.application.name=stats

arduino.api.key=${ARDUINO_API_KEY}
arduino.frontend.api.key=${FRONTEND_API_KEY}
SPRING_DATA_MONGODB_URI=mongodb://${DBMONGO_USER}:${DBMONGO_PASSWORD}@mongo:27017
