spring.application.name=stats
app.arduino-api-key=${ARDUINO_API_KEY}
app.arduino-frontend-api-key=${FRONTEND_API_KEY}
SPRING_DATA_MONGODB_URI=mongodb://${DBMONGO_USER}:${DBMONGO_PASSWORD}@mongo:27017
