spring.config.import=optional:file:./backend-spring/.env[.properties]
server.port=8081
spring.application.name=stats

arduino.api.key=${ARDUINO_API_KEY}
arduino.frontend.api.key=${FRONTEND_API_KEY}
spring.mongodb.uri=mongodb://mongo:27017/climate-data
